### ISSUE TITLE
Too many request for supabase auth

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#75]
Attaching to processor-1
processor-1  | Traceback (most recent call last):
processor-1  |   File "/usr/local/lib/python3.12/site-packages/gotrue/_sync/gotrue_base_api.py", line 120, in _request
processor-1  |     response.raise_for_status()
processor-1  |   File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
processor-1  |     raise HTTPStatusError(message, request=request, response=self)
processor-1  | httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://ijuphmnaebfdzsfrnsrn.supabase.co/auth/v1/token?grant_type=refresh_token'

**Comment by JesJehle** [comment]
https://github.com/supabase/auth-js/issues/454

**Comment by JesJehle** [comment]
again:
processor-1  | Traceback (most recent call last):
processor-1  |   File "/usr/local/lib/python3.12/site-packages/gotrue/_sync/gotrue_base_api.py", line 120, in _request
processor-1  |     response.raise_for_status()
processor-1  |   File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
processor-1  |     raise HTTPStatusError(message, request=request, response=self)
processor-1  | httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://ijuphmnaebfdzsfrnsrn.supabase.co/auth/v1/token?grant_type=refresh_token'
processor-1  | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
processor-1  | 
processor-1  | During handling of the above exception, another exception occurred:
processor-1  | 
processor-1  | Traceback (most recent call last):
processor-1  |   File "/app/run.py", line 30, in <module>
processor-1  |     Fire({'server': run, 'start-queue': background_process})
processor-1  |   File "/usr/local/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
processor-1  |     component_trace = _Fire(component, args, parsed_flag_args, context, name)
processor-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/usr/local/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
processor-1  |     component, remaining_args = _CallAndUpdateTrace(
processor-1  |                                 ^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/usr/local/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
processor-1  |     component = fn(*varargs, **kwargs)
processor-1  |                 ^^^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/app/src/queue.py", line 101, in background_process
processor-1  |     token = login(settings.processor_username, settings.processor_password).session.access_token
processor-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/app/src/supabase.py", line 31, in login
processor-1  |     auth_response = client.auth.refresh_session()
processor-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/usr/local/lib/python3.12/site-packages/gotrue/_sync/gotrue_client.py", line 711, in refresh_session
processor-1  |     session = self._call_refresh_token(refresh_token)
processor-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/usr/local/lib/python3.12/site-packages/gotrue/_sync/gotrue_client.py", line 997, in _call_refresh_token
processor-1  |     response = self._refresh_access_token(refresh_token)
processor-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
processor-1  |   File "/usr/local/lib/python3.12/site-packages/gotrue/_sync/gotrue_client.py", line 1005, in _refresh_access_token
processor-1  |     return self._request(
processor-1  |            ^^^^^^^^^^^^^^
processor-1  |   File "/usr/local/lib/python3.12/site-packages/gotrue/_sync/gotrue_base_api.py", line 125, in _request
processor-1  |     raise handle_exception(e)
processor-1  | gotrue.errors.AuthApiError: Request rate limit reached
